//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DBconn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int AnimalID { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public decimal Weight { get; set; }
        public string FoodPreferences { get; set; }
        public string CareRecommendations { get; set; }
        public int TrainerID { get; set; }
    
        public virtual Trainers Trainers { get; set; }
    }
}
