//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DBconn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists
    {
        public int ArtistID { get; set; }
        public string FullName { get; set; }
        public int SuccessfulPerformances { get; set; }
        public string Type { get; set; }
        public string DressingRoom { get; set; }
    }
}
