//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DBconn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventID { get; set; }
        public string Name { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventType { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> Prepayment { get; set; }
        public string OrganizingCompany { get; set; }
        public bool IsCompleted { get; set; }
        public decimal? NetIncome { get; internal set; }
    }
}
